- upstream: https://pypi.org
  local: 127.0.0.1:9999
  logfile: pypi-index.urls
  headers:
    - name: User-Agent
      value: snoopy/v1
  response-rewrites:
    - old: https://files.pythonhosted.org
      new: http://localhost:9998
      must-rewrite: true
- upstream: https://files.pythonhosted.org
  local: 127.0.0.1:9998
  logfile: pypi-files.urls
